#!/usr/bin/env python3
"""Generate parity documentation from retained release evidence."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from common.correctness_evidence import correctness_report_failures
from common.framework_registry import load_framework_manifest
from scenarios.definitions import SCENARIOS

PROJECT_ROOT = Path(__file__).parent.parent
CORRECTNESS_EVIDENCE = PROJECT_ROOT / "validation" / "CORRECTNESS_RESULTS.json"
LARGE_SCALE_EVIDENCE = PROJECT_ROOT / "validation" / "vectorbt_pro" / "large_scale_parity.json"
TARGETS = (
    PROJECT_ROOT / "README.md",
    PROJECT_ROOT / "docs" / "index.md",
    PROJECT_ROOT / "docs" / "user-guide" / "profiles.md",
    PROJECT_ROOT / "validation" / "README.md",
    PROJECT_ROOT / "validation" / "METHODOLOGY.md",
)
START_MARKER = "<!-- parity-claims:start -->"
END_MARKER = "<!-- parity-claims:end -->"
GITHUB_EVIDENCE_ROOT = "https://github.com/ml4t/backtest/blob/main/validation"
SCENARIO_FRAMEWORKS = load_framework_manifest().scenario_framework_ids


def _load_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise TypeError(f"Evidence must be a JSON object: {path}")
    return payload


def _validate_evidence(correctness: dict[str, Any], large_scale: dict[str, Any]) -> None:
    failures = correctness_report_failures(correctness)
    if failures:
        raise ValueError("Accepted correctness evidence is invalid: " + "; ".join(failures))
    frameworks = correctness.get("frameworks")
    records = correctness.get("records")
    if not isinstance(frameworks, dict) or not isinstance(records, list):
        raise ValueError("Correctness evidence lacks framework pins or records")
    expected = set(SCENARIO_FRAMEWORKS)
    if set(frameworks) != expected:
        raise ValueError("Correctness evidence does not cover the required framework matrix")
    for framework in expected:
        framework_records = [record for record in records if record.get("framework") == framework]
        if len(framework_records) != len(SCENARIOS):
            raise ValueError(f"Expected {len(SCENARIOS)} retained records for {framework}")
    if large_scale.get("exact_comparison", {}).get("passed") is not True:
        raise ValueError("Large-scale evidence is not an exact canonical pass")


def render_claims(correctness: dict[str, Any], large_scale: dict[str, Any]) -> str:
    """Render the canonical documentation block."""
    _validate_evidence(correctness, large_scale)
    frameworks = correctness["frameworks"]
    records = correctness["records"]
    correctness_url = f"{GITHUB_EVIDENCE_ROOT}/CORRECTNESS_RESULTS.json"
    large_scale_url = f"{GITHUB_EVIDENCE_ROOT}/vectorbt_pro/large_scale_parity.json"

    rows = []
    for framework in SCENARIO_FRAMEWORKS:
        pin = frameworks[framework]
        framework_records = [record for record in records if record["framework"] == framework]
        required = [record for record in framework_records if record["required"]]
        passed = [record for record in required if record["status"] == "pass"]
        failures = [record for record in required if record["status"] != "pass"]
        if failures:
            failed_ids = ", ".join(record["scenario_id"] for record in failures)
            result = f"{len(passed)}/{len(required)} pass; blocked by scenario {failed_ids}"
        else:
            result = f"{len(passed)}/{len(required)} exact"
        pinned_framework = f"[{pin['display_name']} {pin['version']}]({pin['source']})"
        rows.append(
            f"| `{pin['profile']}` | {pinned_framework} | {result} | "
            f"[scenario evidence]({correctness_url}) |"
        )

    comparison = large_scale["exact_comparison"]
    reference = large_scale["reference"]
    large_row = (
        f"| `vectorbt_strict` | VectorBT Pro {reference['version']} "
        f"(`{reference['git_commit'][:12]}`) | {comparison['trades']['count']:,} trades | "
        f"0 | {comparison['terminal_value']['reference_canonical']:.6f} | "
        f"[large-scale evidence]({large_scale_url}) |"
    )

    return "\n".join(
        [
            START_MARKER,
            "<!-- Generated by validation/generate_parity_claims.py. Do not edit by hand. -->",
            "",
            'Scenario claims use the retained release-candidate matrix. "Exact" means terminal '
            "values, ordered closed trades, and ordered fills match after 1e-8 quantization for "
            "every retained surface the framework exposes.",
            "",
            "| Profile | Pinned framework | Required scenarios | Evidence |",
            "|---|---|---:|---|",
            *rows,
            "",
            "Large-scale claims are published only when a retained workload has zero canonical gap.",
            "",
            "| Profile | Pinned framework | Compared | Trade gap | Terminal value | Evidence |",
            "|---|---|---:|---:|---:|---|",
            large_row,
            "",
            "No large-scale claim is published for Backtrader, Zipline, VectorBT OSS, or LEAN "
            "without a passing retained artifact.",
            END_MARKER,
        ]
    )


def replace_claims(document: str, claims: str, *, path: Path) -> str:
    """Replace one generated claims block in a document."""
    if document.count(START_MARKER) != 1 or document.count(END_MARKER) != 1:
        raise ValueError(f"Expected exactly one parity claims block in {path}")
    prefix, remainder = document.split(START_MARKER, 1)
    _, suffix = remainder.split(END_MARKER, 1)
    return f"{prefix}{claims}{suffix}"


def synchronize(*, check: bool) -> list[Path]:
    """Write generated blocks or return documents that differ from evidence."""
    claims = render_claims(_load_json(CORRECTNESS_EVIDENCE), _load_json(LARGE_SCALE_EVIDENCE))
    changed: list[Path] = []
    for path in TARGETS:
        current = path.read_text(encoding="utf-8")
        expected = replace_claims(current, claims, path=path)
        if current == expected:
            continue
        changed.append(path)
        if not check:
            path.write_text(expected, encoding="utf-8")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated claims are stale")
    args = parser.parse_args()
    changed = synchronize(check=args.check)
    if args.check and changed:
        print("Parity claims differ from retained evidence:")
        for path in changed:
            print(f"- {path.relative_to(PROJECT_ROOT)}")
        return 1
    if not args.check:
        for path in changed:
            print(f"Updated {path.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
