#!/usr/bin/env python3
"""Deterministic per-bar trace comparator for Backtrader strict parity.

Compares Backtrader vs ml4t-backtest[backtrader_strict] on:
- cash
- positions snapshot
- order intents generated by canonical target logic
- order acceptance/rejection counters (framework-normalized)
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

# Add project root so script can run directly via `python validation/...py`
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from benchmark_suite import (  # noqa: E402
    BenchmarkConfig,
    build_canonical_target_lookup,
    build_canonical_target_shares,
    generate_benchmark_data,
)


def _normalize_date(ts: Any) -> pd.Timestamp:
    t = pd.Timestamp(ts)
    if t.tzinfo is not None:
        t = t.tz_convert(None)
    return t.normalize()


def _fmt_qty(value: float) -> str:
    return f"{float(value):.8f}"


def _positions_signature(positions: dict[str, float]) -> str:
    if not positions:
        return ""
    items = sorted((asset, qty) for asset, qty in positions.items() if abs(qty) > 1e-12)
    return ";".join(f"{asset}:{_fmt_qty(qty)}" for asset, qty in items)


def _intents_signature(intents: list[tuple[str, float, float, float]]) -> str:
    if not intents:
        return ""
    normalized = sorted(
        (asset, _fmt_qty(cur), _fmt_qty(target), _fmt_qty(delta))
        for asset, cur, target, delta in intents
    )
    return ";".join(f"{asset}:{cur}->{target}({delta})" for asset, cur, target, delta in normalized)


def _counter_signature(counter: Counter[str]) -> str:
    if not counter:
        return ""
    items = sorted((asset, int(count)) for asset, count in counter.items() if count)
    return ";".join(f"{asset}:{count}" for asset, count in items)


def _detail_signature(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return ""
    def _key(item: dict[str, Any]) -> tuple[Any, ...]:
        return (
            str(item.get("asset", "")),
            str(item.get("status", "")),
            str(item.get("order_id", "")),
            float(item.get("qty", 0.0)),
            str(item.get("reason", "")),
        )

    parts: list[str] = []
    for item in sorted(rows, key=_key):
        asset = str(item.get("asset", ""))
        status = str(item.get("status", ""))
        order_id = str(item.get("order_id", ""))
        qty = _fmt_qty(float(item.get("qty", 0.0)))
        reason = str(item.get("reason", "")).replace(";", ",")
        parts.append(f"{asset}:{status}:{order_id}:{qty}:{reason}")
    return ";".join(parts)


@dataclass
class TraceResult:
    framework: str
    trace: pd.DataFrame


def run_ml4t_trace(
    config: BenchmarkConfig,
    price_data: dict[str, pd.DataFrame],
    signals: pd.DataFrame,
    dates: pd.DatetimeIndex,
) -> TraceResult:
    import polars as pl

    from ml4t.backtest._validation_imports import BacktestConfig, DataFeed, Engine, Strategy
    from ml4t.backtest.config import CommissionModel, SlippageModel

    asset_names = sorted(price_data.keys())
    target_shares = build_canonical_target_shares(config, signals, dates, asset_names)
    target_lookup_ts = build_canonical_target_lookup(target_shares)
    target_lookup_dt = {ts.to_pydatetime(): targets for ts, targets in target_lookup_ts.items()}

    price_rows = []
    for asset_name, df in price_data.items():
        for ts, row in df.iterrows():
            price_rows.append(
                {
                    "timestamp": ts.to_pydatetime(),
                    "asset": asset_name,
                    "open": row["open"],
                    "high": row["high"],
                    "low": row["low"],
                    "close": row["close"],
                    "volume": row["volume"],
                }
            )
    prices_pl = pl.DataFrame(price_rows)

    signals_pl = pl.DataFrame(
        {
            "timestamp": signals["timestamp"].tolist(),
            "asset": signals["asset"].tolist(),
            "score": signals["score"].tolist(),
        }
    )

    class TraceStrategy(Strategy):
        def __init__(self, target_lookup: dict[pd.Timestamp, dict[str, float]]):
            self.target_lookup = target_lookup
            self.rows: list[dict[str, Any]] = []
            self.events: dict[pd.Timestamp, Counter[str]] = defaultdict(Counter)
            self.event_assets: dict[pd.Timestamp, dict[str, Counter[str]]] = defaultdict(
                lambda: defaultdict(Counter)
            )
            self.event_details: dict[pd.Timestamp, list[dict[str, Any]]] = defaultdict(list)
            self._seen_status: dict[str, str] = {}
            self._submitted_at: dict[str, pd.Timestamp] = {}
            self._rows_by_ts: dict[pd.Timestamp, dict[str, Any]] = {}
            self._submit_accept_assets: dict[pd.Timestamp, Counter[str]] = defaultdict(Counter)
            self._submit_reject_assets: dict[pd.Timestamp, Counter[str]] = defaultdict(Counter)
            self._submit_accept_details: dict[pd.Timestamp, list[dict[str, Any]]] = defaultdict(list)
            self._submit_reject_details: dict[pd.Timestamp, list[dict[str, Any]]] = defaultdict(list)

        def _capture_status_changes(self, ts_key: pd.Timestamp, broker) -> None:
            for order in broker.orders:
                status = order.status.value
                prev = self._seen_status.get(order.order_id)
                if prev is not None and prev != status:
                    self.events[ts_key][status] += 1
                    self.event_assets[ts_key][status][order.asset] += 1
                    qty = order.quantity if order.side.value == "buy" else -order.quantity
                    detail = {
                        "asset": order.asset,
                        "status": status,
                        "order_id": order.order_id,
                        "qty": float(qty),
                        "reason": order.rejection_reason or "",
                    }
                    self.event_details[ts_key].append(detail)
                    if status == "rejected":
                        submit_ts = self._submitted_at.get(order.order_id)
                        if submit_ts is not None and submit_ts in self._rows_by_ts and submit_ts != ts_key:
                            row = self._rows_by_ts[submit_ts]
                            row["submission_rejected_contract"] = int(
                                row.get("submission_rejected_contract", 0)
                            ) + 1
                            self._submit_reject_assets[submit_ts][order.asset] += 1
                            self._submit_reject_details[submit_ts].append(detail)
                self._seen_status[order.order_id] = status

        def finalize_rows(self) -> None:
            for row in self.rows:
                ts_key = row["timestamp"]
                row["event_rejected_assets"] = _counter_signature(
                    self.event_assets[ts_key].get("rejected", Counter())
                )
                row["event_rejected_details"] = _detail_signature(
                    [d for d in self.event_details[ts_key] if d.get("status") == "rejected"]
                )
                row["submission_accepted_assets_local"] = _counter_signature(
                    self._submit_accept_assets[ts_key]
                )
                row["submission_rejected_assets_local"] = _counter_signature(
                    self._submit_reject_assets[ts_key]
                )
                row["submission_accepted_details_local"] = _detail_signature(
                    self._submit_accept_details[ts_key]
                )
                row["submission_rejected_details_local"] = _detail_signature(
                    self._submit_reject_details[ts_key]
                )
                row["submission_accepted_assets_contract"] = _counter_signature(
                    self._submit_accept_assets[ts_key]
                )
                row["submission_rejected_assets_contract"] = _counter_signature(
                    self._submit_reject_assets[ts_key]
                )
                row["submission_rejected_details_contract"] = _detail_signature(
                    self._submit_reject_details[ts_key]
                )

        def on_data(self, timestamp, data, context, broker):
            ts_key = _normalize_date(timestamp)
            self._capture_status_changes(ts_key, broker)

            targets = self.target_lookup.get(pd.Timestamp(timestamp).to_pydatetime(), {})
            active_assets = set(targets.keys())
            active_assets.update(broker.positions.keys())

            intents: list[tuple[str, float, float, float]] = []
            submitted_accepted = 0
            submitted_rejected = 0
            submitted_accepted_assets: Counter[str] = Counter()
            submitted_rejected_assets: Counter[str] = Counter()
            accepted_details: list[dict[str, Any]] = []
            rejected_details: list[dict[str, Any]] = []
            for asset_name in sorted(active_assets):
                position = broker.get_position(asset_name)
                current_qty = position.quantity if position else 0.0
                pending_orders = broker.get_pending_orders(asset_name)
                pending_qty = 0.0
                for pending_order in pending_orders:
                    pending_qty += (
                        pending_order.quantity
                        if pending_order.side.value == "buy"
                        else -pending_order.quantity
                    )
                target_qty = targets.get(asset_name, 0.0)
                delta = target_qty - (current_qty + pending_qty)
                if delta != 0.0:
                    intents.append((asset_name, current_qty, target_qty, delta))
                    if pending_orders:
                        for pending_order in pending_orders:
                            broker.cancel_order(pending_order.order_id)
                    new_order = broker.submit_order(asset_name, target_qty - current_qty)
                    if new_order is not None:
                        self._submitted_at[new_order.order_id] = ts_key
                        self._seen_status[new_order.order_id] = new_order.status.value
                        submit_qty = (
                            new_order.quantity
                            if new_order.side.value == "buy"
                            else -new_order.quantity
                        )
                        detail = {
                            "asset": asset_name,
                            "status": new_order.status.value,
                            "order_id": new_order.order_id,
                            "qty": float(submit_qty),
                            "reason": new_order.rejection_reason or "",
                        }
                        if new_order.status.value == "rejected":
                            submitted_rejected += 1
                            submitted_rejected_assets[asset_name] += 1
                            rejected_details.append(detail)
                        else:
                            submitted_accepted += 1
                            submitted_accepted_assets[asset_name] += 1
                            accepted_details.append(detail)

            pos_snapshot = {
                asset: pos.quantity
                for asset, pos in broker.positions.items()
                if abs(pos.quantity) > 1e-12
            }

            row = {
                "timestamp": ts_key,
                "cash": float(broker.cash),
                "positions_signature": _positions_signature(pos_snapshot),
                "positions_count": len(pos_snapshot),
                "gross_abs_qty": float(sum(abs(q) for q in pos_snapshot.values())),
                "intent_count": len(intents),
                "intents_signature": _intents_signature(intents),
                "event_filled": int(self.events[ts_key].get("filled", 0)),
                "event_rejected": int(self.events[ts_key].get("rejected", 0)),
                "event_cancelled": int(self.events[ts_key].get("cancelled", 0)),
                "submission_accepted_local": submitted_accepted,
                "submission_rejected_local": submitted_rejected,
                "submission_accepted_contract": submitted_accepted,
                "submission_rejected_contract": submitted_rejected,
            }

            self._rows_by_ts[ts_key] = row
            self._submit_accept_assets[ts_key].update(submitted_accepted_assets)
            self._submit_reject_assets[ts_key].update(submitted_rejected_assets)
            self._submit_accept_details[ts_key].extend(accepted_details)
            self._submit_reject_details[ts_key].extend(rejected_details)
            row["submission_accepted"] = submitted_accepted
            row["submission_rejected"] = submitted_rejected

            self.rows.append(row)

    cfg = BacktestConfig.from_preset("backtrader_strict")
    cfg.initial_cash = config.initial_cash
    cfg.allow_short_selling = True
    cfg.commission_model = CommissionModel.NONE
    cfg.commission_rate = 0.0
    cfg.slippage_model = SlippageModel.NONE
    cfg.slippage_rate = 0.0

    feed = DataFeed(prices_df=prices_pl, signals_df=signals_pl)
    strategy = TraceStrategy(target_lookup_dt)
    engine = Engine.from_config(feed, strategy, config=cfg)
    engine.run()
    strategy.finalize_rows()
    trace_df = pd.DataFrame(strategy.rows).sort_values("timestamp").reset_index(drop=True)
    return TraceResult(framework="ml4t_backtrader_strict", trace=trace_df)


def run_backtrader_trace(
    config: BenchmarkConfig,
    price_data: dict[str, pd.DataFrame],
    signals: pd.DataFrame,
    dates: pd.DatetimeIndex,
) -> TraceResult:
    import backtrader as bt

    asset_names = sorted(price_data.keys())
    target_shares = build_canonical_target_shares(config, signals, dates, asset_names)
    target_lookup_raw = build_canonical_target_lookup(target_shares)
    target_lookup = {ts.strftime("%Y-%m-%d"): targets for ts, targets in target_lookup_raw.items()}

    class TraceBTStrategy(bt.Strategy):
        def __init__(self):
            self.target_lookup = target_lookup
            self.data_by_name = {d._name: d for d in self.datas}
            self.rows: list[dict[str, Any]] = []
            self.events: dict[pd.Timestamp, Counter[str]] = defaultdict(Counter)
            self.event_assets: dict[pd.Timestamp, dict[str, Counter[str]]] = defaultdict(
                lambda: defaultdict(Counter)
            )
            self.event_details: dict[pd.Timestamp, list[dict[str, Any]]] = defaultdict(list)

        def notify_order(self, order):
            dt = self.datas[0].datetime.datetime(0)
            ts_key = _normalize_date(dt)
            status_name = order.getstatusname()
            asset_name = getattr(order.data, "_name", "")
            qty = float(getattr(order.created, "size", 0.0))
            self.events[ts_key][status_name] += 1
            self.event_assets[ts_key][status_name][asset_name] += 1
            self.event_details[ts_key].append(
                {
                    "asset": asset_name,
                    "status": status_name,
                    "order_id": str(order.ref),
                    "qty": qty,
                    "reason": "",
                }
            )

        def next(self):
            dt = self.datas[0].datetime.datetime(0)
            ts_key = _normalize_date(dt)
            dt_key = dt.strftime("%Y-%m-%d")
            targets = self.target_lookup.get(dt_key, {})

            active_names = set(targets.keys())
            for data in self.datas:
                if self.getposition(data).size != 0:
                    active_names.add(data._name)

            intents: list[tuple[str, float, float, float]] = []
            for asset_name in sorted(active_names):
                data = self.data_by_name[asset_name]
                current_size = float(self.getposition(data).size)
                target_size = float(targets.get(asset_name, 0.0))
                delta = target_size - current_size
                if delta != 0.0:
                    intents.append((asset_name, current_size, target_size, delta))
                    self.order_target_size(data=data, target=target_size)

            pos_snapshot: dict[str, float] = {}
            for data in self.datas:
                size = float(self.getposition(data).size)
                if abs(size) > 1e-12:
                    pos_snapshot[data._name] = size

            ev = self.events[ts_key]
            accepted_assets = self.event_assets[ts_key].get("Accepted", Counter())
            rejected_assets = Counter(self.event_assets[ts_key].get("Rejected", Counter()))
            rejected_assets.update(self.event_assets[ts_key].get("Margin", Counter()))
            self.rows.append(
                {
                    "timestamp": ts_key,
                    "cash": float(self.broker.getcash()),
                    "positions_signature": _positions_signature(pos_snapshot),
                    "positions_count": len(pos_snapshot),
                    "gross_abs_qty": float(sum(abs(q) for q in pos_snapshot.values())),
                    "intent_count": len(intents),
                    "intents_signature": _intents_signature(intents),
                    "event_submitted": int(ev.get("Submitted", 0)),
                    "event_accepted": int(ev.get("Accepted", 0)),
                    "event_completed": int(ev.get("Completed", 0)),
                    "event_rejected": int(ev.get("Rejected", 0) + ev.get("Margin", 0)),
                    "event_cancelled": int(ev.get("Canceled", 0)),
                    "event_accepted_assets": _counter_signature(accepted_assets),
                    "event_rejected_assets": _counter_signature(rejected_assets),
                    "event_accepted_details": _detail_signature(
                        [d for d in self.event_details[ts_key] if d.get("status") == "Accepted"]
                    ),
                    "event_rejected_details": _detail_signature(
                        [
                            d
                            for d in self.event_details[ts_key]
                            if d.get("status") in {"Rejected", "Margin"}
                        ]
                    ),
                }
            )

    cerebro = bt.Cerebro()
    cerebro.addstrategy(TraceBTStrategy)
    for asset_name, df in price_data.items():
        data = bt.feeds.PandasData(dataname=df, name=asset_name)
        cerebro.adddata(data)
    cerebro.broker.setcash(config.initial_cash)
    results = cerebro.run()

    strategy = results[0]
    trace_df = pd.DataFrame(strategy.rows).sort_values("timestamp").reset_index(drop=True)
    return TraceResult(framework="backtrader", trace=trace_df)


def compare_traces(
    backtrader_trace: pd.DataFrame,
    ml4t_trace: pd.DataFrame,
    cash_tol: float,
) -> tuple[pd.DataFrame, dict[str, Any] | None, dict[str, Any] | None]:
    bt = backtrader_trace.rename(columns=lambda c: f"bt_{c}" if c != "timestamp" else c)
    ml = ml4t_trace.rename(columns=lambda c: f"ml_{c}" if c != "timestamp" else c)
    joined = bt.merge(ml, on="timestamp", how="inner").sort_values("timestamp").reset_index(drop=True)

    # Backtrader notify_order callbacks are observed one bar after submission in this harness.
    # Shift acceptance/rejection to compare against same-day ml4t submission outcomes.
    joined["bt_submit_accepted"] = joined["bt_event_accepted"].shift(-1).fillna(0).astype(int)
    joined["bt_submit_rejected"] = joined["bt_event_rejected"].shift(-1).fillna(0).astype(int)
    joined["bt_submit_cancelled"] = joined["bt_event_cancelled"].shift(-1).fillna(0).astype(int)
    if "bt_event_accepted_assets" in joined.columns:
        joined["bt_submit_accepted_assets"] = (
            joined["bt_event_accepted_assets"].shift(-1).fillna("").astype(str)
        )
    else:
        joined["bt_submit_accepted_assets"] = ""
    if "bt_event_rejected_assets" in joined.columns:
        joined["bt_submit_rejected_assets"] = (
            joined["bt_event_rejected_assets"].shift(-1).fillna("").astype(str)
        )
    else:
        joined["bt_submit_rejected_assets"] = ""
    if "bt_event_accepted_details" in joined.columns:
        joined["bt_submit_accepted_details"] = (
            joined["bt_event_accepted_details"].shift(-1).fillna("").astype(str)
        )
    else:
        joined["bt_submit_accepted_details"] = ""
    if "bt_event_rejected_details" in joined.columns:
        joined["bt_submit_rejected_details"] = (
            joined["bt_event_rejected_details"].shift(-1).fillna("").astype(str)
        )
    else:
        joined["bt_submit_rejected_details"] = ""

    rows: list[dict[str, Any]] = []
    first_divergence: dict[str, Any] | None = None
    first_semantic_divergence: dict[str, Any] | None = None

    last_idx = len(joined) - 1
    for idx, row in joined.iterrows():
        cash_diff = float(row["ml_cash"] - row["bt_cash"])
        pos_match = row["ml_positions_signature"] == row["bt_positions_signature"]
        intent_match = row["ml_intents_signature"] == row["bt_intents_signature"]

        ml_rejected_total = int(
            row.get("ml_submission_rejected_contract", row.get("ml_submission_rejected", 0))
        )
        reject_diff = int(ml_rejected_total - row.get("bt_submit_rejected", 0))
        cancel_diff = int(row.get("ml_event_cancelled", 0) - row.get("bt_submit_cancelled", 0))

        admitted_bt = int(row.get("bt_submit_accepted", 0))
        admitted_ml = int(
            row.get("ml_submission_accepted_contract", row.get("ml_submission_accepted", 0))
        )
        admitted_diff = admitted_ml - admitted_bt
        bt_accepted_assets = str(row.get("bt_submit_accepted_assets", ""))
        bt_rejected_assets = str(row.get("bt_submit_rejected_assets", ""))
        ml_accepted_assets = str(
            row.get("ml_submission_accepted_assets_contract", row.get("ml_submission_accepted_assets_local", ""))
        )
        ml_rejected_assets = str(
            row.get("ml_submission_rejected_assets_contract", row.get("ml_submission_rejected_assets_local", ""))
        )
        bt_accepted_details = str(row.get("bt_submit_accepted_details", ""))
        bt_rejected_details = str(row.get("bt_submit_rejected_details", ""))
        ml_accepted_details = str(
            row.get("ml_submission_accepted_details_local", "")
        )
        ml_rejected_details = str(
            row.get("ml_submission_rejected_details_contract", row.get("ml_submission_rejected_details_local", ""))
        )

        # Last bar has no next-bar notify_order observations to align against.
        if idx == last_idx:
            admitted_bt = admitted_ml
            admitted_diff = 0
            reject_diff = 0
            cancel_diff = 0
            ml_rejected_total = int(row.get("bt_submit_rejected", 0))
            bt_accepted_assets = ml_accepted_assets
            bt_rejected_assets = ml_rejected_assets
            bt_accepted_details = ml_accepted_details
            bt_rejected_details = ml_rejected_details

        semantic_mismatch = abs(cash_diff) > cash_tol or not pos_match or not intent_match

        mismatch = semantic_mismatch or reject_diff != 0 or cancel_diff != 0 or admitted_diff != 0

        out = {
            "timestamp": row["timestamp"],
            "cash_diff": cash_diff,
            "positions_match": pos_match,
            "intents_match": intent_match,
            "semantic_mismatch": semantic_mismatch,
            "admitted_bt": admitted_bt,
            "admitted_ml": admitted_ml,
            "admitted_diff": admitted_diff,
            "reject_diff": reject_diff,
            "cancel_diff": cancel_diff,
            "bt_accepted_assets": bt_accepted_assets,
            "ml_accepted_assets": ml_accepted_assets,
            "bt_rejected_assets": bt_rejected_assets,
            "ml_rejected_assets": ml_rejected_assets,
            "mismatch": mismatch,
        }
        rows.append(out)

        if mismatch and first_divergence is None:
            first_divergence = {
                **out,
                "bt_cash": float(row["bt_cash"]),
                "ml_cash": float(row["ml_cash"]),
                "bt_positions": row["bt_positions_signature"],
                "ml_positions": row["ml_positions_signature"],
                "bt_intents": row["bt_intents_signature"],
                "ml_intents": row["ml_intents_signature"],
                "bt_rejected": int(row.get("bt_submit_rejected", 0)),
                "ml_rejected": ml_rejected_total,
                "bt_cancelled": int(row.get("bt_submit_cancelled", 0)),
                "ml_cancelled": int(row.get("ml_event_cancelled", 0)),
                "bt_accepted_assets": bt_accepted_assets,
                "ml_accepted_assets": ml_accepted_assets,
                "bt_rejected_assets": bt_rejected_assets,
                "ml_rejected_assets": ml_rejected_assets,
                "bt_accepted_details": bt_accepted_details,
                "ml_accepted_details": ml_accepted_details,
                "bt_rejected_details": bt_rejected_details,
                "ml_rejected_details": ml_rejected_details,
            }
        if semantic_mismatch and first_semantic_divergence is None:
            first_semantic_divergence = {
                **out,
                "bt_cash": float(row["bt_cash"]),
                "ml_cash": float(row["ml_cash"]),
                "bt_positions": row["bt_positions_signature"],
                "ml_positions": row["ml_positions_signature"],
                "bt_intents": row["bt_intents_signature"],
                "ml_intents": row["ml_intents_signature"],
                "bt_rejected": int(row.get("bt_submit_rejected", 0)),
                "ml_rejected": ml_rejected_total,
                "bt_cancelled": int(row.get("bt_submit_cancelled", 0)),
                "ml_cancelled": int(row.get("ml_event_cancelled", 0)),
                "bt_accepted_assets": bt_accepted_assets,
                "ml_accepted_assets": ml_accepted_assets,
                "bt_rejected_assets": bt_rejected_assets,
                "ml_rejected_assets": ml_rejected_assets,
                "bt_accepted_details": bt_accepted_details,
                "ml_accepted_details": ml_accepted_details,
                "bt_rejected_details": bt_rejected_details,
                "ml_rejected_details": ml_rejected_details,
            }

    return pd.DataFrame(rows), first_divergence, first_semantic_divergence


def main() -> int:
    parser = argparse.ArgumentParser(description="Deterministic per-bar trace comparator for backtrader_strict")
    parser.add_argument("--bars", type=int, default=1500)
    parser.add_argument("--assets", type=int, default=250)
    parser.add_argument("--top-n", type=int, default=25)
    parser.add_argument("--bottom-n", type=int, default=25)
    parser.add_argument("--seed", type=int, default=123)
    parser.add_argument("--initial-cash", type=float, default=1_000_000.0)
    parser.add_argument("--cash-tol", type=float, default=1e-6)
    parser.add_argument("--max-print-rows", type=int, default=5)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("validation") / "trade_logs" / "trace_compare",
    )
    args = parser.parse_args()

    cfg = BenchmarkConfig(
        name=f"TraceCompare_{args.bars}x{args.assets}",
        n_bars=args.bars,
        n_assets=args.assets,
        frequency="D",
        top_n=args.top_n,
        bottom_n=args.bottom_n,
        rebalance_freq=1,
        initial_cash=args.initial_cash,
    )

    price_data, signals, dates = generate_benchmark_data(cfg, seed=args.seed)

    bt_result = run_backtrader_trace(cfg, price_data, signals, dates)
    ml_result = run_ml4t_trace(cfg, price_data, signals, dates)

    diff_df, first_div, first_semantic_div = compare_traces(
        bt_result.trace, ml_result.trace, cash_tol=args.cash_tol
    )

    args.output_dir.mkdir(parents=True, exist_ok=True)
    bt_path = args.output_dir / f"backtrader_trace_{args.bars}x{args.assets}_seed{args.seed}.csv"
    ml_path = args.output_dir / f"ml4t_trace_{args.bars}x{args.assets}_seed{args.seed}.csv"
    diff_path = args.output_dir / f"trace_diff_{args.bars}x{args.assets}_seed{args.seed}.csv"

    bt_result.trace.to_csv(bt_path, index=False)
    ml_result.trace.to_csv(ml_path, index=False)
    diff_df.to_csv(diff_path, index=False)

    total_rows = len(diff_df)
    mismatch_rows = int(diff_df["mismatch"].sum())

    print("=" * 80)
    print("BACKTRADER STRICT TRACE COMPARATOR")
    print("=" * 80)
    print(f"Scenario: bars={args.bars}, assets={args.assets}, top_n={args.top_n}, bottom_n={args.bottom_n}")
    print(f"Rows compared: {total_rows}")
    print(f"Mismatch rows: {mismatch_rows}")
    print(f"BT trace: {bt_path}")
    print(f"ML trace: {ml_path}")
    print(f"Diff trace: {diff_path}")

    if first_div is None:
        print("No divergence found under selected fields.")
        return 0

    print("\nFirst divergence:")
    print(f"  timestamp: {first_div['timestamp']}")
    print(f"  cash: bt={first_div['bt_cash']:.6f}, ml={first_div['ml_cash']:.6f}, diff={first_div['cash_diff']:.6f}")
    print(f"  admitted: bt={first_div['admitted_bt']}, ml={first_div['admitted_ml']}, diff={first_div['admitted_diff']}")
    print(f"  rejected: bt={first_div['bt_rejected']}, ml={first_div['ml_rejected']}, diff={first_div['reject_diff']}")
    print(f"  cancelled: bt={first_div['bt_cancelled']}, ml={first_div['ml_cancelled']}, diff={first_div['cancel_diff']}")
    print(f"  positions_match: {first_div['positions_match']}")
    print(f"  intents_match: {first_div['intents_match']}")

    print("\nPositions (bt):")
    print(f"  {first_div['bt_positions']}")
    print("Positions (ml):")
    print(f"  {first_div['ml_positions']}")
    print("Intents (bt):")
    print(f"  {first_div['bt_intents']}")
    print("Intents (ml):")
    print(f"  {first_div['ml_intents']}")
    print("Accepted by asset (bt shifted):")
    print(f"  {first_div['bt_accepted_assets']}")
    print("Accepted by asset (ml submit):")
    print(f"  {first_div['ml_accepted_assets']}")
    print("Rejected by asset (bt shifted):")
    print(f"  {first_div['bt_rejected_assets']}")
    print("Rejected by asset (ml submit-contract):")
    print(f"  {first_div['ml_rejected_assets']}")
    print("Accepted details (bt shifted):")
    print(f"  {first_div['bt_accepted_details']}")
    print("Accepted details (ml submit):")
    print(f"  {first_div['ml_accepted_details']}")
    print("Rejected details (bt shifted):")
    print(f"  {first_div['bt_rejected_details']}")
    print("Rejected details (ml submit-contract):")
    print(f"  {first_div['ml_rejected_details']}")

    if first_semantic_div is not None:
        print("\nFirst semantic divergence (cash/positions/intents):")
        print(f"  timestamp: {first_semantic_div['timestamp']}")
        print(
            "  cash: "
            f"bt={first_semantic_div['bt_cash']:.6f}, "
            f"ml={first_semantic_div['ml_cash']:.6f}, "
            f"diff={first_semantic_div['cash_diff']:.6f}"
        )
        print(f"  positions_match: {first_semantic_div['positions_match']}")
        print(f"  intents_match: {first_semantic_div['intents_match']}")
        print("  rejected by asset (bt shifted):")
        print(f"    {first_semantic_div['bt_rejected_assets']}")
        print("  rejected by asset (ml submit-contract):")
        print(f"    {first_semantic_div['ml_rejected_assets']}")
        print("  rejected details (bt shifted):")
        print(f"    {first_semantic_div['bt_rejected_details']}")
        print("  rejected details (ml submit-contract):")
        print(f"    {first_semantic_div['ml_rejected_details']}")

    print("\nNearby mismatches:")
    mismatch_view = diff_df[diff_df["mismatch"]].head(args.max_print_rows)
    print(mismatch_view.to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
